In [5]:
from lib.models.losses import FocalLoss
import lib.models.losses

In [127]:
import torch
import torch.nn as nn
import torch.nn.functional as F
crit_ss = torch.nn.CrossEntropyLoss() 

In [114]:
pred = torch.randn((10,80,180,180))
gt = torch.randn((10,80,180,180))
print(pred.size())

torch.Size([10, 80, 180, 180])


In [54]:
A = F.one_hot(torch.arange(0, 180*180)%80, num_classes=80)
print(A.size())

torch.Size([32400, 80])


In [124]:
i = 0
for x in range(180):
    for y in range(180):
        for z in range(10):
            pred[z,:,x,y] = A[i]
            gt[z,:,x,y] = A[180*180-i-1]
        i+=1

In [ ]:
crit_ss(pred[], gt[])

In [138]:
def _Cross_loss(pred,gt): #size: batch x classes x w x h = batch x classes x 180 x 180
    loss = 0
    for i in range(180):
        for k in range(180):
            for j in range(10):
                loss += crit_ss(pred[j,:,i,k],torch.argmax(gt[j,:,i,k]))
    return loss/(180*180*10)
    

In [141]:
crit_ss(torch.argmax(pred[0,:,0,0]), pred[0,:,0,0])

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [139]:
_Cross_loss(pred,gt)

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [143]:
loss = nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
print(input)
target = torch.empty(3, dtype=torch.long).random_(5)
print(target)
output = loss(input, target)
print(output)

tensor([[ 0.9891,  0.0136,  1.2443, -2.7386, -0.4670],
        [-0.5882,  0.8608, -1.3864, -0.2145, -0.1458],
        [-0.0687, -0.1847, -0.6656,  0.5836, -2.0812]], requires_grad=True)
tensor([2, 4, 1])
tensor(1.3867, grad_fn=<NllLossBackward>)


In [170]:
print(pred.size())
print(labels2.size())

torch.Size([10, 80, 180, 180])
torch.Size([10, 180, 180])


In [185]:
pred[:,:,0,0].size()

torch.Size([10, 80])

In [179]:
labels2[:,0,0].size()

torch.Size([10])

In [181]:
loss(pred[:,:,0,0],labels2[:,0,0])

tensor(3.4033)

In [169]:
loss(pred,labels2)

tensor(3.3896)

In [164]:
labels = torch.argmax(gt,dim=1)#torch.Size([10, 180, 180])
labels2 = torch.argmax(pred,dim=1)#torch.Size([10, 180, 180])

In [159]:
gt[0,:,0,1]

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0.])